import { ChatPreviewData } from "./type";

const MOCK: ChatPreviewData[] = [
  {
    id: "1",
    type: "direct",
    name: "John Doe",
    lastMessage: "Hey there!",
    lastUser: "John Doe",
    timestamp: new Date(),
  },
  {
    id: "2",
    type: "group",
    name: "Frontend Team",
    lastMessage: "Let's deploy now.",
    lastUser: "Alice",
    timestamp: new Date(),
  },
  {
    id: "3",
    type: "direct",
    name: "Jane Smith",
    lastMessage: "Catch up later?",
    lastUser: "Jane Smith",
    timestamp: new Date(),
  },
  {
    id: "4",
    type: "group",
    name: "Backend Team",
    lastMessage: "Issue resolved!",
    lastUser: "Bob",
    timestamp: new Date(),
  },
  {
    id: "5",
    type: "direct",
    name: "Mike Ross",
    lastMessage: "Review this PR please.",
    lastUser: "Mike Ross",
    timestamp: new Date(),
  },
  {
    id: "6",
    type: "group",
    name: "Marketing",
    lastMessage: "Meeting at 3 PM.",
    lastUser: "Sarah",
    timestamp: new Date(),
  },
  {
    id: "7",
    type: "direct",
    name: "Harvey Specter",
    lastMessage: "Done.",
    lastUser: "Harvey Specter",
    timestamp: new Date(),
  },
  {
    id: "8",
    type: "group",
    name: "Sales Team",
    lastMessage: "Target achieved!",
    lastUser: "Louis",
    timestamp: new Date(),
  },
  {
    id: "9",
    type: "direct",
    name: "Rachel Zane",
    lastMessage: "Thanks!",
    lastUser: "Rachel Zane",
    timestamp: new Date(),
  },
  {
    id: "10",
    type: "group",
    name: "UX Designers",
    lastMessage: "New prototype ready.",
    lastUser: "Donna",
    timestamp: new Date(),
  },
  {
    id: "11",
    type: "direct",
    name: "Tom Hanks",
    lastMessage: "Let's talk tomorrow.",
    lastUser: "Tom Hanks",
    timestamp: new Date(),
  },
  {
    id: "12",
    type: "group",
    name: "Product Team",
    lastMessage: "Feature approved.",
    lastUser: "Emily",
    timestamp: new Date(),
  },
  {
    id: "13",
    type: "direct",
    name: "Emma Watson",
    lastMessage: "Got it!",
    lastUser: "Emma Watson",
    timestamp: new Date(),
  },
  {
    id: "14",
    type: "group",
    name: "Developers",
    lastMessage: "Release notes updated.",
    lastUser: "Oscar",
    timestamp: new Date(),
  },
  {
    id: "15",
    type: "direct",
    name: "Chris Evans",
    lastMessage: "LOL",
    lastUser: "Chris Evans",
    timestamp: new Date(),
  },
  {
    id: "16",
    type: "group",
    name: "Support",
    lastMessage: "Ticket closed.",
    lastUser: "Nancy",
    timestamp: new Date(),
  },
  {
    id: "17",
    type: "direct",
    name: "Scarlett Johansson",
    lastMessage: "Sure thing.",
    lastUser: "Scarlett Johansson",
    timestamp: new Date(),
  },
  {
    id: "18",
    type: "group",
    name: "QA Team",
    lastMessage: "Bug found.",
    lastUser: "Peter",
    timestamp: new Date(),
  },
  {
    id: "19",
    type: "direct",
    name: "Robert Downey",
    lastMessage: "Perfect!",
    lastUser: "Robert Downey",
    timestamp: new Date(),
  },
  {
    id: "20",
    type: "group",
    name: "DevOps",
    lastMessage: "Server restarted.",
    lastUser: "Bruce",
    timestamp: new Date(),
  },
];

export default MOCK;
